config:
  #If it's enabled, it will kick new accounts not allowed
  #0 means is allowed 1 player per ip
  enable-kick: true
  allowed-alts: 0
  #If a player with alts joins, send message to all ops in the server
  join-message: true
  #If it's false, if an op player joins it won't be sended
  join-message-op: false
messages:
  kick-message: ""