main: mc.jabi14.AltsViewer
version: 2.0
name: AltsViewer
author: Jabi14

commands:
  alts:
    view:
      description: View players alts
      ipview:
        description: View ip accounts
    description: Main command of altsviewer